In [1]:
import numpy as np

In [3]:
x = np.array([3,4,5])
y = np.array([4,9,7])
# treats them as matrices
print(x + y)

[ 7 13 12]


In [4]:
x = np.array([[1,2],[3,4]])
# follows the structure
print(x)

[[1 2]
 [3 4]]


In [5]:
# shows the number of dimensions
print(x.ndim)

2


In [6]:
# shows the type
print(x.dtype)
z = np.array([[1 , 2],[42,53],[54,2]])
print(z.dtype)

int64
int64


In [7]:
# shows the number of rows and columns
print(z.shape)

(3, 2)


In [8]:
# dont need to use print here
z

array([[ 1,  2],
       [42, 53],
       [54,  2]])

In [9]:
# reshapes the data as long as it fits
print(z.reshape(2,3))
print()
print(z.reshape(1,6))

[[ 1  2 42]
 [53 54  2]]

[[ 1  2 42 53 54  2]]


In [10]:
# swaps the rows and cols aka transpose
print(z)
print()
print(z.T)

[[ 1  2]
 [42 53]
 [54  2]]

[[ 1 42 54]
 [ 2 53  2]]


In [ ]:
# generates the square root of the entries
np.sqrt(z)
# or x**0.5

In [ ]:
# generates the square of the elements
z**2

In [ ]:
# generates a single random number
np.random.normal?

In [ ]:
# generates a 1 row matrix with 50 datapoints
x = np.random.normal(size = 50)
x

In [ ]:
# if given loc, it generates noise from that loc 50
y = x + np.random.normal(loc=50,scale=1, size=50)
y

In [ ]:
# the off-diagnol element shows and computes the correlation coefficient matrix between x and y.

np.corrcoef(x,y)